### ISSUE TITLE
Problem with maven repository

### ISSUE THREAD

**Issue by airton-soares** [jatecs/jatecs#7]
It looks like your maven repository ir off. The "pom.xml" file says **Missing artifact hlt.isti.cnr.it:jatecs-gpl:jar:1.0.0**.
I have done every steps in the "README.md" file.
I am using eclipse.

**Comment by aesuli** [comment]
It seems that github has changed the way to link raw files.
The repo url must be changed from 
`<url>https://raw.github.com/jatecs/jatecs/mvn-repo/</url>`
to
`<url>https://github.com/jatecs/jatecs/raw/mvn-repo/</url>`
I have updated the README.md file.

**Comment by airton-soares** [comment]
Thanks
